### ISSUE TITLE
Finalize version 1 of Version Control System Strategy

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#641] opened 2020-01-27 19:51 UTC
- Create a story

What's the roadmap
Who pays 
Where does the credit go 
Once implemented, then what?
What are the benefits, how do we show them? How quickly?
etc... 

- Alignment with DOSP and https://www.tbs-sct.gc.ca/pol/doc-eng.aspx?id=15249

**Comment by remyb2canada** [comment] 2020-10-28 14:29
duplicate of xxxxx

**Closed by remyb2canada** 2020-10-28 14:29 UTC
Labels: strategies
