### ISSUE TITLE
Reach out to GCTools

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#1159] opened 2020-08-05 13:39 UTC

**Comment by gabrielcossette** [comment] 2020-08-13 21:44
@jaysonmc I also contacted GCTools :) Sorry again.

**Comment by jaysonmc** [comment] 2020-08-19 13:07
Duplicate of https://github.com/sara-sabr/ITStrategy/issues/641?

**Closed** 2020-09-17 12:59 UTC
