### ISSUE TITLE
Digital Policy Briefing Note

### ISSUE THREAD

**Issue by gabrielcossette** [sara-sabr/ITStrategy#131] opened 2019-07-23 18:01 UTC
From DS request (email from Martin 2019-05-27)
Produce a briefing note on the effect of the new Policy on Service and Digital
Received SSPB contact from CDO & SSPB Policy Research.

Draft produced on the [internal sharepoint site here](http://dialogue/grp/BU6810070/Shared%20Documents/Debriefs/Executive%20Briefing%20on%20the%20TBS%20Digital%20Policy.docx)

[Briefing note and deck here](http://dialogue/grp/BU6810070/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fgrp%2FBU6810070%2FShared%20Documents%2FDebriefs&FolderCTID=0x012000750E51FFC3799647B0714B66227C003A&View={DA914447-F5A7-44BD-89E1-9ECB3B44185A})

**Draft BriefingNote**
- [ ] Review BF

**Debrief**
- [x] Draft BF
- [x] Setup kickoff meeting with SSPB (John Slocombe, Clara Morgan, Jeff Knight)
- [ ] Review BF with SSPB
- [ ] Make changes
- [ ] Review BF by DS
- [x] Attend TBS/ESDC meeting to discuss Digital Policy (Fri June 21)

**Comment by smellems** [comment] 2019-10-09 12:19
Is this a duplicate of #232 ?

**Closed** 2019-10-09 13:25 UTC
Labels: policies
