### ISSUE TITLE
Hackathon - Brainstorm Themes and Ideas

### ISSUE THREAD

**Issue by myp192** [sara-sabr/ITStrategy#572] opened 2020-01-13 16:24 UTC
Hackathon rescheduled for October 2020. 
Summary of the discussion : 

Workshops and Learning 
	- Breaking in the silos 
	- SA's should be in it

Recommended Topics
	- Accessibility of the tools 
	- Non technical stuff 
	- Security Could be around opening up their sharepoint and cleaning it up
- aligns with Work in the Open
- Information management
- Security

People IITB
	- Outcome 
	- Demographic : IITB - who is more in the technical field 
Workshops targeted on th

**Comment by smellems** [comment] 2020-01-13 16:32
Duplicate of #573

**Closed by smellems** 2020-01-13 16:32 UTC
