### ISSUE TITLE
Add page counters to pages on Strategy site

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#257] opened 2019-09-17 14:13 UTC
Iteration 1 

Each time a user visits a page, increment a counter by 1 to keep track of which pages are visited and which are not. 

Not a very good metric, but better than no metrics (which is what we have now).

**Comment by smellems** [comment] 2019-10-09 12:25
Duplicate of #272

**Closed by smellems** 2019-10-09 12:25 UTC
Labels: enhancement
