### ISSUE TITLE
Automate detection of contradictions in documents

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITStrategy#507] opened 2019-12-17 12:39 UTC
Could run against all SharePoint docs or add into our pipeline

https://www.google.com/url?sa=t&source=web&rct=j&url=https://nlp.stanford.edu/pubs/contradiction-acl08.pdf&ved=2ahUKEwjs2ZCO2bzmAhUIVs0KHYXgCHEQFjAAegQIBxAC&usg=AOvVaw3_lGInU1wyC7SOj21px-5N&cshid=1576586176432

**Comment by smellems** [comment] 2020-07-22 14:14
Duplicate of #1098

**Closed by smellems** 2020-07-22 14:14 UTC
Labels: Enabling
