### ISSUE TITLE
fix mobile rendering

### ISSUE THREAD

**Issue by remyb2canada** [sara-sabr/ITStrategy#2018] opened 2022-02-02 00:17 UTC
Viewing the site (e.g. blogs) over mobile does not render correctly.

E.g. this on a mobile phone does not fit the text correctly: 

https://sara-sabr.github.io/ITStrategy/2021/12/10/iitb-diagnostic-study.html

https://sara-sabr.github.io/ITStrategy/2021/10/15/product-management-part-2.html

**Comment by smellems** [comment] 2022-12-13 18:56
Duplicate of #2021

**Closed by smellems** 2022-12-13 18:56 UTC
Labels: Accessibility
